package BD;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import TVSR.Som;
import TVSR.Eventos;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class ListaProgramas extends javax.swing.JDialog {

    /**
     * Creates new form ListaProgramas
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    conexao con_BD;
    private static ArrayList<Eventos> eventos;

    public ListaProgramas(ArrayList<Eventos> ev) {
        eventos = ev;
        setModal(true);
        initComponents();
        update_tabLP();

    }

    public void update_tabLP() {
        con_BD = new conexao();
        con_BD.conecta();
        try {
            rs = con_BD.executeSQL("select nome_prog as Nome,data_prog as Data, hora_inic_prog as Hora, Canal from bd_tvsr");
            tabela.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "BURACO!");
        }
        JBt_ListComplet.setEnabled(false);
        jLabel9.setText("Nº de Programas = " + tabela.getRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        TvSReminderPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TvSReminderPU").createEntityManager();
        bdTvsrQuery = java.beans.Beans.isDesignTime() ? null : TvSReminderPUEntityManager.createQuery("SELECT DISTINCT b.canal FROM BdTvsr b");
        bdTvsrList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : bdTvsrQuery.getResultList();
        bdTvsrQuery1 = java.beans.Beans.isDesignTime() ? null : TvSReminderPUEntityManager.createQuery("SELECT DISTINCT b.generoProg FROM BdTvsr b");
        bdTvsrList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : bdTvsrQuery1.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        procurar = new javax.swing.JButton();
        Proc = new javax.swing.JTextField();
        jCBCanais = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCBGenero = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        adicionar = new javax.swing.JButton();
        JBt_ListComplet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Programas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName(""); // NOI18N

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Programa", "Data", "Hora", "Canal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(0).setHeaderValue("Programa");
        tabela.getColumnModel().getColumn(1).setHeaderValue("Data/Hora");
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(2).setHeaderValue("Canal");

        jLabel1.setText("Lista de programas");

        procurar.setText("Procurar");
        procurar.setPreferredSize(new java.awt.Dimension(80, 23));
        procurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                procurarMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                procurarMousePressed(evt);
            }
        });
        procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bdTvsrList, jCBCanais);
        bindingGroup.addBinding(jComboBoxBinding);

        jCBCanais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCanaisActionPerformed(evt);
            }
        });

        jLabel2.setText("Listar por:");

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bdTvsrList1, jCBGenero);
        bindingGroup.addBinding(jComboBoxBinding);

        jCBGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGeneroActionPerformed(evt);
            }
        });

        jLabel9.setText("Nº de programas:");

        adicionar.setText("Adicionar evento");
        adicionar.setEnabled(false);
        adicionar.setPreferredSize(new java.awt.Dimension(80, 23));
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        JBt_ListComplet.setText("Lista completa");
        JBt_ListComplet.setEnabled(false);
        JBt_ListComplet.setPreferredSize(new java.awt.Dimension(80, 23));
        JBt_ListComplet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBt_ListCompletMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBt_ListComplet, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCBGenero, 0, 157, Short.MAX_VALUE)
                                .addComponent(jCBCanais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Proc)))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(JBt_ListComplet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(jCBCanais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(Proc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("");

        jButton1.setText("Cancelar");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBCanaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCanaisActionPerformed
        String SCanal = String.valueOf(jCBCanais.getSelectedItem());

        try {
            rs = con_BD.executeSQL("SELECT nome_prog as Nome,data_prog as Data, hora_inic_prog as Hora, Canal FROM bd_tvsr WHERE canal LIKE '" + SCanal + "'");
            tabela.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
        JBt_ListComplet.setEnabled(true);
        jLabel9.setText("Nº de Programas = " + tabela.getRowCount());

    }//GEN-LAST:event_jCBCanaisActionPerformed

    private void procurarMouseReleased(java.awt.event.MouseEvent evt) {

        String titulo = String.valueOf(Proc.getText());

        try {
            rs = con_BD.executeSQL("select nome_prog as Nome,data_prog as Data, hora_inic_prog as Hora, Canal from bd_tvsr where nome_prog LIKE '%" + titulo + "%'");
            tabela.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
        JBt_ListComplet.setEnabled(true);
        jLabel9.setText("Nº de Programas = " + tabela.getRowCount());
    }

    private void jCBGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGeneroActionPerformed
        String SGenero = String.valueOf(jCBGenero.getSelectedItem());

        try {
            rs = con_BD.executeSQL("SELECT nome_prog as Nome,data_prog as Data, hora_inic_prog as Hora, Canal FROM bd_tvsr WHERE genero_prog LIKE '" + SGenero + "'");
            tabela.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }

        JBt_ListComplet.setEnabled(true);
        jLabel9.setText("Nº de Programas = " + tabela.getRowCount());

    }//GEN-LAST:event_jCBGeneroActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void JBt_ListCompletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBt_ListCompletMouseClicked
        update_tabLP();
    }//GEN-LAST:event_JBt_ListCompletMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    }//GEN-LAST:event_jButton1MouseClicked

    private void procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarActionPerformed
    }//GEN-LAST:event_procurarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            adicionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        boolean flag = false;
        if (tabela.getSelectedRow() != -1) {
            Eventos e = new Eventos(tabela.getModel().getValueAt(tabela.getSelectedRow(), 0).toString(), tabela.getModel().getValueAt(tabela.getSelectedRow(), 1).toString(), tabela.getModel().getValueAt(tabela.getSelectedRow(), 2).toString(), tabela.getModel().getValueAt(tabela.getSelectedRow(), 3).toString());
            for (int i = 0; i < eventos.size(); i++) {
                if (new String(eventos.get(i).getNome().toString()).equals(e.getNome().toString())
                        && new String(eventos.get(i).getData().toString()).equals(e.getData().toString())
                        && new String(eventos.get(i).getHora().toString()).equals(e.getHora().toString())) {
                    JOptionPane.showMessageDialog(null,
                            "Programa já se encontra na sua lista!",
                            "Error ao adicionar",
                            JOptionPane.ERROR_MESSAGE);
                    flag = true;
                }
            }
            //começa
            try {
                Calendar cal = Calendar.getInstance();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date data1 = df.parse(df.format(cal.getTime()));
                java.util.Date data2 = df.parse(e.getData());
                if (data1.before(data2)) {
                    flag = true;
                    JOptionPane.showMessageDialog(null, "Evento já passou!!!!");
                } else if (data1.equals(data2)) {
                    SimpleDateFormat hf = new SimpleDateFormat("HH:mm:ss");

                    java.util.Date dh1 = hf.parse(e.getHora());
                    java.util.Date dh2 = hf.parse(hf.format(cal.getTime()));
                    if (dh1.before(dh2)) {
                        flag = true;
                        JOptionPane.showMessageDialog(null, "Evento já passou!!!!");
                    }
                }
            } catch (ParseException pe) {
            }
            //acaba
            if (!flag) {
                JOptionPane.showMessageDialog(null,
                        "Programa adicionado com sucesso!",
                        "Adicionado",
                        JOptionPane.PLAIN_MESSAGE);
                eventos.add(e);
            }
        }
    }//GEN-LAST:event_adicionarActionPerformed

    private void procurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaProgramas(eventos).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBt_ListComplet;
    private javax.swing.JTextField Proc;
    private javax.persistence.EntityManager TvSReminderPUEntityManager;
    private javax.swing.JButton adicionar;
    private java.util.List<BD.BdTvsr> bdTvsrList;
    private java.util.List<BD.BdTvsr> bdTvsrList1;
    private javax.persistence.Query bdTvsrQuery;
    private javax.persistence.Query bdTvsrQuery1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBCanais;
    private javax.swing.JComboBox jCBGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton procurar;
    private javax.swing.JTable tabela;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
